var attr = DS.attr,
    hasMany = DS.hasMany,
    belongsTo = DS.belongsTo;

var Toilet = DS.Model.extend({
  title: attr('string'),
  accessible: attr('boolean'),
  male: attr('boolean'),
  female: attr('boolean'),
  unisex: attr('boolean'),
  babyChange: attr('boolean'),
  ratings: hasMany('rating'),
  sharps: attr('boolean'),
  showers: attr('boolean'),
  sanitaryDisposal: attr('boolean'),
  geoX: attr('number'),
  geoY: attr('number')
});

Toilet.reopenClass({
  FIXTURES: [
  {
    id: "1",
    title: 'Southbank Promenade (opposite Esso House)',
    accessible: true,
    male: true,
    female: true,
    unisex: true,
    babyChange: true,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8203421290366,
    geoY: 144.964219727982
  },
  {
    id: "3",
    title: 'Flinders Street Station',
    accessible: true,
    male: true,
    female: true,
    unisex: true,
    babyChange: false,
    sharps: true,
    showers: false,
    sanitaryDisposal: true,
    geoX: -37.817792,
    geoY: 144.96722917
  },
  {
    id: "4",
    title: 'Lonsdale Street (Opposite 88 Lonsdale Street)',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8100356799286,
    geoY: 144.969902463305
  },
  {
    id: "5",
    title: 'Flagstaff Gardens (cnr William & Dudley)',
    accessible: true,
    male: true,
    female: true,
    unisex: true,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8089204751149,
    geoY: 144.955043308784
  },
  {
    id: "6",
    title: 'Saint Mangos Lane, The Palladio (New Quay)',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.814358311416,
    geoY: 144.941682166969
  },
  {
    id: "7",
    title: 'Public Toilet -Southern Cross Station',
    accessible: true,
    male: true,
    female: true,
    unisex: true,
    babyChange: true,
    sharps: true,
    showers: false,
    sanitaryDisposal: true,
    geoX: -37.817792,
    geoY: 144.96722917
  },
  {
    id: "8",
    title: 'Alexandra Gardens (Riverslide Skate Park)',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8203552732817,
    geoY: 144.973312908294
  },
  {
    id: "9",
    title: 'Birrarung Marr Speakers Corner',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8210047801156,
    geoY: 144.975933223872
  },
  {
    id: "10",
    title: 'Exhibition Street (Opposite 242 Exhibition Street)',
    accessible: false,
    male: true,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8095460463599,
    geoY: 144.969407118569
  },
  {
    id: "11",
    title: 'Queen Victoria Market (465 Queen Street)',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: true,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: 37.8078639954478,
    geoY: 144.966424039606
  },
  {
    id: "12",
    title: 'Corner of King & Lonsdale Streets',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: true,
    sharps: true,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8144895,
    geoY: 144.9548398
  },
  {
    id: "13",
    title: 'Melbourne Central Station',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: true,
    sharps: true,
    showers: false,
    sanitaryDisposal: true,
    geoX: -37.81005,
    geoY: 144.9628
  },
  {
    id: "14",
    title: 'Gordon Reserve (74-108 Spring Street)',
    accessible: true,
    male: false,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8122407760326,
    geoY: 144.97392555857
  },
  {
    id: "15",
    title: 'Treasury Gardens (Store and Toilet)',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8134184349012,
    geoY: 144.977467007735
  },
  {
    id: "16",
    title: 'Carlton Gardens South (Opposite 39 Rathdowne Street)',
    accessible: true,
    male: true,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8062589327935,
    geoY: 144.969202702206
  },
  {
    id: "17",
    title: 'Franklin Street (Opposite 80 Franklin Street)',
    accessible: true,
    male: true,
    female: true,
    unisex: true,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8082354509674,
    geoY: 144.96018982974
  },
  {
    id: "18",
    title: 'Queensberry Street (Adjacent 179 Queensberry Street)',
    accessible: false,
    male: true,
    female: false,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: -37.8046418038556,
    geoY: 144.962850161271
  },
  {
    id: "19",
    title: 'Parliament Station  - City Loop ',
    accessible:  true,
    male: true,
    female: false,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    geoX: 37.8114,
    geoY: 144.9731
  },
  {
    id: "20",
    title: 'Powlett  Street Reserve - East Melbourne ',
    accessible:  true,
    male: true,
    female: false,
    unisex: false,
    babyChange: false,
    sharps: false,
    showers: false,
    sanitaryDisposal: false,
    drinkingWater: false,
    geoX: -37.4847,
    geoY: 144.5906
  },
  {
    id: "21",
    title: 'Gosch\'s Paddock, Yarra Park ',
    accessible:  true,
    male: true,
    female: true,
    unisex: false,
    babyChange: false,
    sharps: true,
    showers: false,
    sanitaryDisposal: false,
    drinkingWater: false,
    geoX: -37.4905,
    geoY: 144.5907
  }
]});

export default Toilet;
